#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 16000

// Duplex I2S 模式 (INMP441 + MAX98357 共用 BCLK=18, WS=17，严禁定义 AUDIO_I2S_METHOD_SIMPLEX)
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_18
#define AUDIO_I2S_GPIO_WS   GPIO_NUM_17
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_21 // INMP441 SD (麦克风数据输入)
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_6  // MAX98357 DIN (扬声器数据输出)
#define AUDIO_I2S_SPK_SD_PIN GPIO_NUM_7 // MAX98357 SD 使能 (拉高开启功放)

// 主屏：ZAVE 1.3寸 SH1106 OLED (硬件 I2C0)
#define DISPLAY_SDA_PIN GPIO_NUM_8
#define DISPLAY_SCL_PIN GPIO_NUM_9
#define DISPLAY_WIDTH   128
#define DISPLAY_HEIGHT  64
#define SH1106

#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y true

// 继电器与按键
#define LAMP_GPIO        GPIO_NUM_5
#define RELAY_GPIO_PIN   GPIO_NUM_5
#define BOOT_BUTTON_GPIO GPIO_NUM_0      // 板载 BOOT 按键 (GPIO 0)
#define EXT_BUTTON_GPIO  GPIO_NUM_10     // 外接对话按键 (GPIO 10)
#define TOUCH_BUTTON_GPIO GPIO_NUM_11    // 触控/对讲按键 (GPIO 11)
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_NC
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC
#define BUILTIN_LED_GPIO        GPIO_NUM_NC

#endif // _BOARD_CONFIG_H_
