name: Build S3-Cyber Board

on:
  workflow_dispatch:
  push:

permissions:
  contents: read

jobs:
  build:
    name: Build S3 Cyber Firmware
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:v6.1
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Build S3 Cyber
        shell: bash
        run: |
          source $IDF_PATH/export.sh
          python scripts/build.py s3-cyber --name s3-cyber

      - name: Upload merged binary
        uses: actions/upload-artifact@v7
        with:
          name: s3-cyber-firmware
          path: build/merged-binary.bin
          if-no-files-found: error
